### ISSUE TITLE
Add details about company accounts vs personal accounts

### ISSUE THREAD

**Issue by Clorith** [Clorith/wporg-support-guidelines#14]
We really don't like it when users have multiple accounts, but we understand the need for a company account to "own" your plugin.

Add a new section to the FAQ about using Support Representatives for assets you put on WordPress.org

**Comment by Ipstenu** [comment]
Helpful links

https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/
https://developer.wordpress.org/plugins/wordpress-org/using-the-forums/

**Comment by Clorith** [comment]
Added in ef420d762fdd638cae0be0fd923c5eac3d505504 and linked to the handbook references to reduce the amount of maintenance burden here.
