### ISSUE TITLE
Guideline 15, dupe?

### ISSUE THREAD

**Issue by anevins12** [Clorith/wporg-support-guidelines#18]
Are these teh same rules:
**This** Do not abuse mentions, they are not a tool to get faster responses.
...
**And this** Do not abuse the @ mention system in the forums. Users on this site can subscribe to a topic, using @ notifications for your replies in unnecessary and can become spammy and abusive. Please use it sparingly

**Comment by Clorith** [comment]
You are absolutely right, it's a duplicate, fixed in b4ad0dccf501911d34cdac8d3a0af5a012b3c2fa
