### ISSUE TITLE
Move to a FAQ

### ISSUE THREAD

**Issue by Ipstenu** [Clorith/wporg-support-guidelines#3]
All these can be moved to a FAQ and linked in the intro. "If you're new to posting..."

* Search Before Posting
* Finding Posts 
* Post In the Best Place
* Choose A Good Topic Title
* Tag Topics Wisely
* Include as Much Information as Possible
* Link to The Site
* Post Code Safely
* Posting Large Excerpt of Code
* Deleting / Editing Posts
* Deleting / Editing Reviews
* Deleting Accounts

A user FAQ is a good thing :)

**Comment by Clorith** [comment]
I think this is a good idea, they are items that aren't really (in many cases) a violation, but rather a nuisance when it happens, but not something we should punish a user for (for lack of a better term).

Having a separate FAQ page, much in the same spirit as the guidelines and forum welcome page is probably the best approach here. Linking to the handbook is sub-optimal, at least in its current state, as it too is a bit mountainous and could do with an audit and refactor at some point.

I'm thinking `/support/guidelines/faq` as the path, although I'm not convinced, as it's not really an FAQ about the guidelines them selves, but if we leave it at `/support/faq` it just feels like it would be frequently asked questions from support-seeking users, which definitely gives the wrong context. Thoughts on a home for this are more than welcome.

**Comment by Ipstenu** [comment]
Maybe ... `/support/user-guide/faq` then?

So `user-guide` is a handbook for users?

**Comment by Clorith** [comment]
FAQ file has been created here, so closing this out now.
