### ISSUE TITLE
New Guidelines (condensed!)

### ISSUE THREAD

**Issue by Ipstenu** [Clorith/wporg-support-guidelines#4]
You'll notice there are very FEW guidelines now! THAT'S GOOD! Getting bogged down by the minuta is wasting time and energy. They also don't serve a benefit. If you find you're spelling out details to try and explain to someone that they're breaking rules, _they are being a sea lion_ and you need to step back.

Don't spend energy trying to detail out every permutation. People will rules-lawyer you and get around them.

Get the HEART of each guideline, what it means, WHY we give a damn about signatures. If we can't think of why we care too much about a thing, maybe we don't need it. (Signatures fall under 'don't spam' by the way).

These are the body of the actual guidelines. The things people need to know to get them to keep in line.

1. Warn About Adult Content
1. Don't Spam (this includes "Do Not Advertise or Promote Products" and "Avoid Signatures")
1. Do Not Bump Posts 
1. Do Not Offer to Pay for Help
1. Do Not Offer to Work For Hire
1. Do Not Post About Commercial Products
1. Do Not Open Multiple Accounts (Sockpuppets)
1. The Bad Stuff... (see not below)

----

About **the bad stuff....** Most of it fits into other groups and can be broken out into a better organization of topics. So I propose adding these additional guidelines to the above list:

1. Do not put yourself at risk - I lump those together since the real point of them is when you invite internet strangers to log in to YOUR site, you put yourself at risk. And when you log into other people's sites, you take responsibility blah blah blah. Needs a better name, mind you, but you get the idea. This is a GROUP of things you don't do because it's risky and gets you hacked (or sued)
 * Do not post email addresses...
 * Do not post login information...
 * Do not ask for any kind of access ...
 * Do not seek legal advice ...
2. Do not harass people
 * Do not post another person’s private information ...
 * Do not harass or abuse people....
 * Do not abuse mentions ...
 * Do not abuse the @ mention system in the forums (why do we have this twice anyway?)
3. Don't use the forums as your blog - Here we can also add in not to use the forums as your soapbox stuff.
 * Do not post simply to request feedback on their site.
4. Don't be mean - includes "offensive posts, posts without content, or flames."
5. Don't pile on posts - This can cover the whole "Don't use other people's posts to get help on unrelated issues, it's better to make your own post blah blah)

That leaves these:

* Do not post in all caps (belongs in a how to post FAQ)
* Do not ask for help regarding premium themes/plugins (already covered)
* Do not post spam and affiliate links, offensive posts, posts without content, or flames. (already covered)

**Comment by tobifjellner** [comment]
Under "don't harass people" - should we include "Don't "follow home""?

**Comment by Clorith** [comment]
#15 has been merged with the changes proposed here, so I'm closing this ticket, thank you all! 💯
