### ISSUE TITLE
guideline-06 Linking to The site

### ISSUE THREAD

**Issue by richardvd91** [Clorith/wporg-support-guidelines#6]
When creating a Topic a user can give 1 URL that is hidden from Google and is only visible to logged-in users in the "Link to the page you need help with:" text box.

So maybe the new text should be something like this

---

If a question relates to a specific site or page, and the site is publicly viewable, provide a link. This will allow people to see the issue and often leads to faster resolutions. The best way to do this is by using the "_Link to the page you need help with:_" field, this URL is only visible to logged-in users and hidden from search engines. 

The forum is not designed to be a link portal; excessive linkage will be moderated, as will signatures or links with no associated question.

Links will not get removed any time later, unless in extreme circumstances. Google will capture links from the text field, so if that is a concern, please don’t link.

**Comment by Clorith** [comment]
I know this has been proposed somewhere before, and I can't remember if I was enthusiastic about it or not, but someone mentioned it may be beneficial to include a single sentence under the link field in the post form to explain that this is the only link that will be private. If we do that, we can likely remove this guideline in its entirety.

**Comment by Clorith** [comment]
We've initially moved this into the FAQ section, this with a better explanation of the field on the forums them selves should address this :)
